/path/to/mlir-opt /path/to/input_mlir -o /path/to/output_mlir \
-canonicalize \
-one-shot-bufferize="copy-before-write bufferize-function-boundaries function-boundary-type-conversion=identity-layout-map" \
-buffer-deallocation-pipeline \
-convert-linalg-to-affine-loops \
-lower-affine \
-canonicalize \
-expand-strided-metadata \
-convert-scf-to-cf \
-finalize-memref-to-llvm \
-convert-cf-to-llvm \
-convert-math-to-llvm \
-convert-arith-to-llvm \
-convert-func-to-llvm \
-reconcile-unrealized-casts